import type { AppleTheme } from './types'
import { appleTypography } from './typography'

/**
 * Apple HIG dark theme — iOS/macOS dark appearance.
 * Colors sourced from Apple Human Interface Guidelines (iOS 18+).
 *
 * @see https://developer.apple.com/design/human-interface-guidelines/color
 */
export const appleDarkTheme: AppleTheme = {
  colors: {
    tint: '#0A84FF',
    label: '#FFFFFF',
    secondaryLabel: '#EBEBF5',
    tertiaryLabel: '#EBEBF5',
    quaternaryLabel: '#EBEBF5',
    systemBackground: '#000000',
    secondarySystemBackground: '#1C1C1E',
    tertiarySystemBackground: '#2C2C2E',
    systemGroupedBackground: '#000000',
    secondarySystemGroupedBackground: '#1C1C1E',
    tertiarySystemGroupedBackground: '#2C2C2E',
    separator: '#545458',
    opaqueSeparator: '#38383A',
    link: '#0A84FF',
    systemFill: '#787880',
    secondarySystemFill: '#787880',
    tertiarySystemFill: '#767680',
    quaternarySystemFill: '#747480',
    systemRed: '#FF453A',
    systemOrange: '#FF9F0A',
    systemYellow: '#FFD60A',
    systemGreen: '#30D158',
    systemMint: '#63E6E2',
    systemTeal: '#40CBE0',
    systemCyan: '#64D2FF',
    systemBlue: '#0A84FF',
    systemIndigo: '#5E5CE6',
    systemPurple: '#BF5AF2',
    systemPink: '#FF375F',
    systemBrown: '#AC8E68',
    systemGray: '#8E8E93',
    systemGray2: '#636366',
    systemGray3: '#48484A',
    systemGray4: '#3A3A3C',
    systemGray5: '#2C2C2E',
    systemGray6: '#1C1C1E',
  },
  typography: appleTypography,
  shape: {
    cornerNone: 0,
    cornerExtraSmall: 4,
    cornerSmall: 8,
    cornerMedium: 12,
    cornerLarge: 16,
    cornerExtraLarge: 22,
    cornerFull: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 32,
  },
  stateLayer: {
    pressedOpacity: 0.2,
    focusedOpacity: 0.15,
    hoveredOpacity: 0.1,
    disabledOpacity: 0.3,
  },
  elevation: {
    level0: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    level1: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 1,
    },
    level2: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 3,
    },
    level3: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 6,
    },
  },
  motion: {
    durationShort1: 100,
    durationShort2: 150,
    durationShort3: 200,
    durationShort4: 250,
    durationMedium1: 300,
    durationMedium2: 350,
    durationMedium3: 400,
    durationMedium4: 450,
    durationLong1: 500,
    durationLong2: 600,
    durationLong3: 700,
    durationLong4: 800,
    easingLinear: 'cubic-bezier(0, 0, 1, 1)',
    easingStandard: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
    easingStandardAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
    easingStandardDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
    easingEmphasized: 'cubic-bezier(0.22, 1, 0.36, 1)',
    easingEmphasizedAccelerate: 'cubic-bezier(0.4, 0, 0.2, 1)',
    easingEmphasizedDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
  },
}
