import type { AppleTheme } from './types'
import { appleTypography } from './typography'

/**
 * Apple HIG light theme — iOS/macOS light appearance.
 * Colors sourced from Apple Human Interface Guidelines (iOS 18+).
 *
 * @see https://developer.apple.com/design/human-interface-guidelines/color
 */
export const appleLightTheme: AppleTheme = {
  colors: {
    tint: '#007AFF',
    label: '#000000',
    secondaryLabel: '#3C3C43',
    tertiaryLabel: '#3C3C43',
    quaternaryLabel: '#3C3C43',
    systemBackground: '#FFFFFF',
    secondarySystemBackground: '#F2F2F7',
    tertiarySystemBackground: '#FFFFFF',
    systemGroupedBackground: '#F2F2F7',
    secondarySystemGroupedBackground: '#FFFFFF',
    tertiarySystemGroupedBackground: '#F2F2F7',
    separator: '#3C3C43',
    opaqueSeparator: '#C6C6C8',
    link: '#007AFF',
    systemFill: '#787880',
    secondarySystemFill: '#787880',
    tertiarySystemFill: '#767680',
    quaternarySystemFill: '#747480',
    systemRed: '#FF3B30',
    systemOrange: '#FF9500',
    systemYellow: '#FFCC00',
    systemGreen: '#34C759',
    systemMint: '#00C7BE',
    systemTeal: '#30B0C7',
    systemCyan: '#32ADE6',
    systemBlue: '#007AFF',
    systemIndigo: '#5856D6',
    systemPurple: '#AF52DE',
    systemPink: '#FF2D55',
    systemBrown: '#A2845E',
    systemGray: '#8E8E93',
    systemGray2: '#AEAEB2',
    systemGray3: '#C7C7CC',
    systemGray4: '#D1D1D6',
    systemGray5: '#E5E5EA',
    systemGray6: '#F2F2F7',
  },
  typography: appleTypography,
  shape: {
    cornerNone: 0,
    cornerExtraSmall: 4,
    cornerSmall: 8,
    cornerMedium: 12,
    cornerLarge: 16,
    cornerExtraLarge: 22,
    cornerFull: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 32,
  },
  stateLayer: {
    pressedOpacity: 0.2,
    focusedOpacity: 0.15,
    hoveredOpacity: 0.1,
    disabledOpacity: 0.3,
  },
  elevation: {
    level0: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    level1: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
      elevation: 1,
    },
    level2: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
      elevation: 3,
    },
    level3: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 6,
    },
  },
  motion: {
    durationShort1: 100,
    durationShort2: 150,
    durationShort3: 200,
    durationShort4: 250,
    durationMedium1: 300,
    durationMedium2: 350,
    durationMedium3: 400,
    durationMedium4: 450,
    durationLong1: 500,
    durationLong2: 600,
    durationLong3: 700,
    durationLong4: 800,
    easingLinear: 'cubic-bezier(0, 0, 1, 1)',
    easingStandard: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
    easingStandardAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
    easingStandardDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
    easingEmphasized: 'cubic-bezier(0.22, 1, 0.36, 1)',
    easingEmphasizedAccelerate: 'cubic-bezier(0.4, 0, 0.2, 1)',
    easingEmphasizedDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
  },
}
